// Code generated by wit-bindgen-go. DO NOT EDIT.

package config

import (
	"go.bytecodealliance.org/cm"
)

// This file contains wasmimport and wasmexport declarations for "fermyon:spin".

//go:wasmimport fermyon:spin/config get-config
//go:noescape
func wasmimport_GetConfig(key0 *uint8, key1 uint32, result *cm.Result[ErrorShape, string, Error])
