// Code generated by wit-bindgen-go. DO NOT EDIT.

package keyvalue

import (
	"go.bytecodealliance.org/cm"
)

// This file contains wasmimport and wasmexport declarations for "fermyon:spin@2.0.0".

//go:wasmimport fermyon:spin/key-value@2.0.0 [resource-drop]store
//go:noescape
func wasmimport_StoreResourceDrop(self0 uint32)

//go:wasmimport fermyon:spin/key-value@2.0.0 [static]store.open
//go:noescape
func wasmimport_StoreOpen(label0 *uint8, label1 uint32, result *cm.Result[ErrorShape, Store, Error])

//go:wasmimport fermyon:spin/key-value@2.0.0 [method]store.delete
//go:noescape
func wasmimport_StoreDelete(self0 uint32, key0 *uint8, key1 uint32, result *cm.Result[Error, struct{}, Error])

//go:wasmimport fermyon:spin/key-value@2.0.0 [method]store.exists
//go:noescape
func wasmimport_StoreExists(self0 uint32, key0 *uint8, key1 uint32, result *cm.Result[ErrorShape, bool, Error])

//go:wasmimport fermyon:spin/key-value@2.0.0 [method]store.get
//go:noescape
func wasmimport_StoreGet(self0 uint32, key0 *uint8, key1 uint32, result *cm.Result[OptionListU8Shape, cm.Option[cm.List[uint8]], Error])

//go:wasmimport fermyon:spin/key-value@2.0.0 [method]store.get-keys
//go:noescape
func wasmimport_StoreGetKeys(self0 uint32, result *cm.Result[ErrorShape, cm.List[string], Error])

//go:wasmimport fermyon:spin/key-value@2.0.0 [method]store.set
//go:noescape
func wasmimport_StoreSet(self0 uint32, key0 *uint8, key1 uint32, value0 *uint8, value1 uint32, result *cm.Result[Error, struct{}, Error])
