// Code generated by wit-bindgen-go. DO NOT EDIT.

package variables

import (
	"go.bytecodealliance.org/cm"
)

// This file contains wasmimport and wasmexport declarations for "fermyon:spin@2.0.0".

//go:wasmimport fermyon:spin/variables@2.0.0 get
//go:noescape
func wasmimport_Get(name0 *uint8, name1 uint32, result *cm.Result[ErrorShape, string, Error])
