// Code generated by wit-bindgen-go. DO NOT EDIT.

// Package postgres represents the imported interface "fermyon:spin/postgres@2.0.0".
package postgres

import (
	rdbmstypes "github.com/fermyon/spin-go-sdk/v2/internal/fermyon/spin/v2.0.0/rdbms-types"
	"go.bytecodealliance.org/cm"
)

// ParameterValue represents the type alias "fermyon:spin/postgres@2.0.0#parameter-value".
//
// See [rdbmstypes.ParameterValue] for more information.
type ParameterValue = rdbmstypes.ParameterValue

// RowSet represents the type alias "fermyon:spin/postgres@2.0.0#row-set".
//
// See [rdbmstypes.RowSet] for more information.
type RowSet = rdbmstypes.RowSet

// Error represents the type alias "fermyon:spin/postgres@2.0.0#error".
//
// See [rdbmstypes.Error] for more information.
type Error = rdbmstypes.Error

// Connection represents the imported resource "fermyon:spin/postgres@2.0.0#connection".
//
// A connection to a postgres database.
//
//	resource connection
type Connection cm.Resource

// ResourceDrop represents the imported resource-drop for resource "connection".
//
// Drops a resource handle.
//
//go:nosplit
func (self Connection) ResourceDrop() {
	self0 := cm.Reinterpret[uint32](self)
	wasmimport_ConnectionResourceDrop((uint32)(self0))
	return
}

// ConnectionOpen represents the imported static function "open".
//
// Open a connection to the Postgres instance at `address`.
//
//	open: static func(address: string) -> result<connection, error>
//
//go:nosplit
func ConnectionOpen(address string) (result cm.Result[ErrorShape, Connection, Error]) {
	address0, address1 := cm.LowerString(address)
	wasmimport_ConnectionOpen((*uint8)(address0), (uint32)(address1), &result)
	return
}

// Execute represents the imported method "execute".
//
// Execute command to the database.
//
//	execute: func(statement: string, params: list<parameter-value>) -> result<u64,
//	error>
//
//go:nosplit
func (self Connection) Execute(statement string, params cm.List[ParameterValue]) (result cm.Result[ErrorShape, uint64, Error]) {
	self0 := cm.Reinterpret[uint32](self)
	statement0, statement1 := cm.LowerString(statement)
	params0, params1 := cm.LowerList(params)
	wasmimport_ConnectionExecute((uint32)(self0), (*uint8)(statement0), (uint32)(statement1), (*ParameterValue)(params0), (uint32)(params1), &result)
	return
}

// Query represents the imported method "query".
//
// Query the database.
//
//	query: func(statement: string, params: list<parameter-value>) -> result<row-set,
//	error>
//
//go:nosplit
func (self Connection) Query(statement string, params cm.List[ParameterValue]) (result cm.Result[RowSetShape, RowSet, Error]) {
	self0 := cm.Reinterpret[uint32](self)
	statement0, statement1 := cm.LowerString(statement)
	params0, params1 := cm.LowerList(params)
	wasmimport_ConnectionQuery((uint32)(self0), (*uint8)(statement0), (uint32)(statement1), (*ParameterValue)(params0), (uint32)(params1), &result)
	return
}
