// Code generated by wit-bindgen-go. DO NOT EDIT.

package inboundhttp

// This file contains wasmimport and wasmexport declarations for "fermyon:spin".

//go:wasmexport fermyon:spin/inbound-http#handle-request
//export fermyon:spin/inbound-http#handle-request
func wasmexport_HandleRequest(req0 uint32, req1 *uint8, req2 uint32, req3 *[2]string, req4 uint32, req5 *[2]string, req6 uint32, req7 uint32, req8 *uint8, req9 uint32) (result *Response) {
	req := lift_Request((uint32)(req0), (*uint8)(req1), (uint32)(req2), (*[2]string)(req3), (uint32)(req4), (*[2]string)(req5), (uint32)(req6), (uint32)(req7), (*uint8)(req8), (uint32)(req9))
	result_ := Exports.HandleRequest(req)
	result = &result_
	return
}
