// Code generated by wit-bindgen-go. DO NOT EDIT.

// Package inboundhttp represents the exported interface "fermyon:spin/inbound-http".
package inboundhttp

import (
	httptypes "github.com/fermyon/spin-go-sdk/v2/internal/fermyon/spin/http-types"
)

// Request represents the type alias "fermyon:spin/inbound-http#request".
//
// See [httptypes.Request] for more information.
type Request = httptypes.Request

// Response represents the type alias "fermyon:spin/inbound-http#response".
//
// See [httptypes.Response] for more information.
type Response = httptypes.Response
