// Code generated by wit-bindgen-go. DO NOT EDIT.

package inboundhttp

// Exports represents the caller-defined exports from "fermyon:spin/inbound-http".
var Exports struct {
	// HandleRequest represents the caller-defined, exported function "handle-request".
	//
	//	handle-request: func(req: request) -> response
	HandleRequest func(req Request) (result Response)
}
