// Code generated by wit-bindgen-go. DO NOT EDIT.

// Package http represents the imported interface "fermyon:spin/http".
package http

import (
	httptypes "github.com/fermyon/spin-go-sdk/v2/internal/fermyon/spin/http-types"
	"go.bytecodealliance.org/cm"
)

// Request represents the type alias "fermyon:spin/http#request".
//
// See [httptypes.Request] for more information.
type Request = httptypes.Request

// Response represents the type alias "fermyon:spin/http#response".
//
// See [httptypes.Response] for more information.
type Response = httptypes.Response

// HTTPError represents the type alias "fermyon:spin/http#http-error".
//
// See [httptypes.HTTPError] for more information.
type HTTPError = httptypes.HTTPError

// SendRequest represents the imported function "send-request".
//
//	send-request: func(req: request) -> result<response, http-error>
//
//go:nosplit
func SendRequest(req Request) (result cm.Result[ResponseShape, Response, HTTPError]) {
	req0, req1, req2, req3, req4, req5, req6, req7, req8, req9 := lower_Request(req)
	wasmimport_SendRequest((uint32)(req0), (*uint8)(req1), (uint32)(req2), (*[2]string)(req3), (uint32)(req4), (*[2]string)(req5), (uint32)(req6), (uint32)(req7), (*uint8)(req8), (uint32)(req9), &result)
	return
}
