// Code generated by wit-bindgen-go. DO NOT EDIT.

package http

import (
	"go.bytecodealliance.org/cm"
)

// This file contains wasmimport and wasmexport declarations for "fermyon:spin".

//go:wasmimport fermyon:spin/http send-request
//go:noescape
func wasmimport_SendRequest(req0 uint32, req1 *uint8, req2 uint32, req3 *[2]string, req4 uint32, req5 *[2]string, req6 uint32, req7 uint32, req8 *uint8, req9 uint32, result *cm.Result[ResponseShape, Response, HTTPError])
