// Code generated by wit-bindgen-go. DO NOT EDIT.

package sqlite

import (
	"go.bytecodealliance.org/cm"
)

// This file contains wasmimport and wasmexport declarations for "fermyon:spin@2.0.0".

//go:wasmimport fermyon:spin/sqlite@2.0.0 [resource-drop]connection
//go:noescape
func wasmimport_ConnectionResourceDrop(self0 uint32)

//go:wasmimport fermyon:spin/sqlite@2.0.0 [static]connection.open
//go:noescape
func wasmimport_ConnectionOpen(database0 *uint8, database1 uint32, result *cm.Result[ErrorShape, Connection, Error])

//go:wasmimport fermyon:spin/sqlite@2.0.0 [method]connection.execute
//go:noescape
func wasmimport_ConnectionExecute(self0 uint32, statement0 *uint8, statement1 uint32, parameters0 *Value, parameters1 uint32, result *cm.Result[QueryResultShape, QueryResult, Error])
