// Code generated by wit-bindgen-go. DO NOT EDIT.

//go:build !wasip1

package http

import (
	httptypes "github.com/fermyon/spin-go-sdk/internal/fermyon/spin/http-types"
	"github.com/ydnar/wasm-tools-go/cm"
	"unsafe"
)

// ResponseShape is used for storage in variant or result types.
type ResponseShape struct {
	shape [unsafe.Sizeof(httptypes.Response{})]byte
}

func lower_OptionBody(v cm.Option[httptypes.Body]) (f0 uint32, f1 *uint8, f2 uint32) {
	some := v.Some()
	if some != nil {
		f0 = 1
		v1, v2 := cm.LowerList(*some)
		f1 = (*uint8)(v1)
		f2 = (uint32)(v2)
	}
	return
}

func lower_Request(v httptypes.Request) (f0 uint32, f1 *uint8, f2 uint32, f3 *[2]string, f4 uint32, f5 *[2]string, f6 uint32, f7 uint32, f8 *uint8, f9 uint32) {
	f0 = (uint32)(v.Method)
	f1, f2 = cm.LowerString(v.URI)
	f3, f4 = cm.LowerList(v.Headers)
	f5, f6 = cm.LowerList(v.Params)
	f7, f8, f9 = lower_OptionBody(v.Body)
	return
}
