// Code generated by wit-bindgen-go. DO NOT EDIT.

//go:build !wasip1

package redistypes

import (
	"unsafe"
)

// PayloadShape is used for storage in variant or result types.
type PayloadShape struct {
	shape [unsafe.Sizeof(Payload{})]byte
}
