spin_manifest_version = 2

[application]
authors = ["Fermyon Engineering <engineering@fermyon.com>"]
description = "A simple Spin application written in (Tiny)Go that performs outbound HTTP requests."
name = "http-outbound-example"
version = "1.0.0"

[[trigger.http]]
route = "/hello"
component = "hello"

[[trigger.http]]
route = "/http-to-same-app"
component = "http-to-same-app"

[component.hello]
source = "hello/main.wasm"
allowed_outbound_hosts = [
  "https://random-data-api.fermyon.app:443",
  "https://postman-echo.com:443",
]
[component.hello.build]
workdir = "hello"
command = "tinygo build -target=wasi -gc=leaking -no-debug -o main.wasm main.go"

[component.http-to-same-app]
source = "http-to-same-app/main.wasm"
# Use self to make outbound requests to components in the same Spin application.
allowed_outbound_hosts = ["http://self"]
[component.http-to-same-app.build]
workdir = "http-to-same-app"
command = "tinygo build -target=wasi -gc=leaking -no-debug -o main.wasm main.go"
