// Code generated by wit-bindgen-go. DO NOT EDIT.

package sqlite

import (
	"go.bytecodealliance.org/cm"
)

// This file contains wasmimport and wasmexport declarations for "fermyon:spin".

//go:wasmimport fermyon:spin/sqlite open
//go:noescape
func wasmimport_Open(database0 *uint8, database1 uint32, result *cm.Result[ErrorShape, Connection, Error])

//go:wasmimport fermyon:spin/sqlite execute
//go:noescape
func wasmimport_Execute(conn0 uint32, statement0 *uint8, statement1 uint32, parameters0 *Value, parameters1 uint32, result *cm.Result[QueryResultShape, QueryResult, Error])

//go:wasmimport fermyon:spin/sqlite close
//go:noescape
func wasmimport_Close(conn0 uint32)
