// Code generated by wit-bindgen-go. DO NOT EDIT.

//go:build !wasip1

package postgres

import (
	rdbmstypes "github.com/fermyon/spin-go-sdk/internal/fermyon/spin/v2.0.0/rdbms-types"
	"unsafe"
)

// ErrorShape is used for storage in variant or result types.
type ErrorShape struct {
	shape [unsafe.Sizeof(rdbmstypes.Error{})]byte
}

// RowSetShape is used for storage in variant or result types.
type RowSetShape struct {
	shape [unsafe.Sizeof(rdbmstypes.RowSet{})]byte
}
