// Code generated by wit-bindgen-go. DO NOT EDIT.

//go:build !wasip1

package sqlite

import (
	"unsafe"
)

// ErrorShape is used for storage in variant or result types.
type ErrorShape struct {
	shape [unsafe.Sizeof(Error{})]byte
}

// QueryResultShape is used for storage in variant or result types.
type QueryResultShape struct {
	shape [unsafe.Sizeof(QueryResult{})]byte
}
