// Code generated by wit-bindgen-go. DO NOT EDIT.

//go:build !wasip1

package redis

import (
	redistypes "github.com/fermyon/spin-go-sdk/internal/fermyon/spin/redis-types"
	"github.com/ydnar/wasm-tools-go/cm"
	"unsafe"
)

// PayloadShape is used for storage in variant or result types.
type PayloadShape struct {
	shape [unsafe.Sizeof(redistypes.Payload{})]byte
}

// ListStringShape is used for storage in variant or result types.
type ListStringShape struct {
	shape [unsafe.Sizeof(cm.List[string]{})]byte
}

// ListRedisResultShape is used for storage in variant or result types.
type ListRedisResultShape struct {
	shape [unsafe.Sizeof(cm.List[redistypes.RedisResult]{})]byte
}
