// Code generated by wit-bindgen-go. DO NOT EDIT.

package mysql

import (
	"go.bytecodealliance.org/cm"
)

// This file contains wasmimport and wasmexport declarations for "fermyon:spin".

//go:wasmimport fermyon:spin/mysql query
//go:noescape
func wasmimport_Query(address0 *uint8, address1 uint32, statement0 *uint8, statement1 uint32, params0 *ParameterValue, params1 uint32, result *cm.Result[RowSetShape, RowSet, MysqlError])

//go:wasmimport fermyon:spin/mysql execute
//go:noescape
func wasmimport_Execute(address0 *uint8, address1 uint32, statement0 *uint8, statement1 uint32, params0 *ParameterValue, params1 uint32, result *cm.Result[MysqlError, struct{}, MysqlError])
