// Code generated by wit-bindgen-go. DO NOT EDIT.

package redis

import (
	"go.bytecodealliance.org/cm"
	"unsafe"
)

// ErrorShape is used for storage in variant or result types.
type ErrorShape struct {
	_     cm.HostLayout
	shape [unsafe.Sizeof(Error{})]byte
}

// OptionPayloadShape is used for storage in variant or result types.
type OptionPayloadShape struct {
	_     cm.HostLayout
	shape [unsafe.Sizeof(cm.Option[Payload]{})]byte
}
