// Code generated by wit-bindgen-go. DO NOT EDIT.

// Package redis represents the imported interface "fermyon:spin/redis@2.0.0".
package redis

import (
	"go.bytecodealliance.org/cm"
)

// Error represents the variant "fermyon:spin/redis@2.0.0#error".
//
// Errors related to interacting with Redis
//
//	variant error {
//		invalid-address,
//		too-many-connections,
//		type-error,
//		other(string),
//	}
type Error cm.Variant[uint8, string, string]

// ErrorInvalidAddress returns a [Error] of case "invalid-address".
//
// An invalid address string
func ErrorInvalidAddress() Error {
	var data struct{}
	return cm.New[Error](0, data)
}

// InvalidAddress returns true if [Error] represents the variant case "invalid-address".
func (self *Error) InvalidAddress() bool {
	return self.Tag() == 0
}

// ErrorTooManyConnections returns a [Error] of case "too-many-connections".
//
// There are too many open connections
func ErrorTooManyConnections() Error {
	var data struct{}
	return cm.New[Error](1, data)
}

// TooManyConnections returns true if [Error] represents the variant case "too-many-connections".
func (self *Error) TooManyConnections() bool {
	return self.Tag() == 1
}

// ErrorTypeError returns a [Error] of case "type-error".
//
// A retrieved value was not of the correct type
func ErrorTypeError() Error {
	var data struct{}
	return cm.New[Error](2, data)
}

// TypeError returns true if [Error] represents the variant case "type-error".
func (self *Error) TypeError() bool {
	return self.Tag() == 2
}

// ErrorOther returns a [Error] of case "other".
//
// Some other error occurred
func ErrorOther(data string) Error {
	return cm.New[Error](3, data)
}

// Other returns a non-nil *[string] if [Error] represents the variant case "other".
func (self *Error) Other() *string {
	return cm.Case[string](self, 3)
}

var stringsError = [4]string{
	"invalid-address",
	"too-many-connections",
	"type-error",
	"other",
}

// String implements [fmt.Stringer], returning the variant case name of v.
func (v Error) String() string {
	return stringsError[v.Tag()]
}

// Connection represents the imported resource "fermyon:spin/redis@2.0.0#connection".
//
//	resource connection
type Connection cm.Resource

// ResourceDrop represents the imported resource-drop for resource "connection".
//
// Drops a resource handle.
//
//go:nosplit
func (self Connection) ResourceDrop() {
	self0 := cm.Reinterpret[uint32](self)
	wasmimport_ConnectionResourceDrop((uint32)(self0))
	return
}

// ConnectionOpen represents the imported static function "open".
//
// Open a connection to the Redis instance at `address`.
//
//	open: static func(address: string) -> result<connection, error>
//
//go:nosplit
func ConnectionOpen(address string) (result cm.Result[ErrorShape, Connection, Error]) {
	address0, address1 := cm.LowerString(address)
	wasmimport_ConnectionOpen((*uint8)(address0), (uint32)(address1), &result)
	return
}

// Del represents the imported method "del".
//
// Removes the specified keys.
//
// A key is ignored if it does not exist. Returns the number of keys deleted.
//
//	del: func(keys: list<string>) -> result<u32, error>
//
//go:nosplit
func (self Connection) Del(keys cm.List[string]) (result cm.Result[ErrorShape, uint32, Error]) {
	self0 := cm.Reinterpret[uint32](self)
	keys0, keys1 := cm.LowerList(keys)
	wasmimport_ConnectionDel((uint32)(self0), (*string)(keys0), (uint32)(keys1), &result)
	return
}

// Execute represents the imported method "execute".
//
// Execute an arbitrary Redis command and receive the result.
//
//	execute: func(command: string, arguments: list<redis-parameter>) -> result<list<redis-result>,
//	error>
//
//go:nosplit
func (self Connection) Execute(command string, arguments cm.List[RedisParameter]) (result cm.Result[ErrorShape, cm.List[RedisResult], Error]) {
	self0 := cm.Reinterpret[uint32](self)
	command0, command1 := cm.LowerString(command)
	arguments0, arguments1 := cm.LowerList(arguments)
	wasmimport_ConnectionExecute((uint32)(self0), (*uint8)(command0), (uint32)(command1), (*RedisParameter)(arguments0), (uint32)(arguments1), &result)
	return
}

// Get represents the imported method "get".
//
// Get the value of a key.
//
//	get: func(key: string) -> result<option<payload>, error>
//
//go:nosplit
func (self Connection) Get(key string) (result cm.Result[OptionPayloadShape, cm.Option[Payload], Error]) {
	self0 := cm.Reinterpret[uint32](self)
	key0, key1 := cm.LowerString(key)
	wasmimport_ConnectionGet((uint32)(self0), (*uint8)(key0), (uint32)(key1), &result)
	return
}

// Incr represents the imported method "incr".
//
// Increments the number stored at key by one.
//
// If the key does not exist, it is set to 0 before performing the operation.
// An `error::type-error` is returned if the key contains a value of the wrong type
// or contains a string that can not be represented as integer.
//
//	incr: func(key: string) -> result<s64, error>
//
//go:nosplit
func (self Connection) Incr(key string) (result cm.Result[ErrorShape, int64, Error]) {
	self0 := cm.Reinterpret[uint32](self)
	key0, key1 := cm.LowerString(key)
	wasmimport_ConnectionIncr((uint32)(self0), (*uint8)(key0), (uint32)(key1), &result)
	return
}

// Publish represents the imported method "publish".
//
// Publish a Redis message to the specified channel.
//
//	publish: func(channel: string, payload: payload) -> result<_, error>
//
//go:nosplit
func (self Connection) Publish(channel string, payload Payload) (result cm.Result[Error, struct{}, Error]) {
	self0 := cm.Reinterpret[uint32](self)
	channel0, channel1 := cm.LowerString(channel)
	payload0, payload1 := cm.LowerList(payload)
	wasmimport_ConnectionPublish((uint32)(self0), (*uint8)(channel0), (uint32)(channel1), (*uint8)(payload0), (uint32)(payload1), &result)
	return
}

// Sadd represents the imported method "sadd".
//
// Add the specified `values` to the set named `key`, returning the number of newly-added
// values.
//
//	sadd: func(key: string, values: list<string>) -> result<u32, error>
//
//go:nosplit
func (self Connection) Sadd(key string, values cm.List[string]) (result cm.Result[ErrorShape, uint32, Error]) {
	self0 := cm.Reinterpret[uint32](self)
	key0, key1 := cm.LowerString(key)
	values0, values1 := cm.LowerList(values)
	wasmimport_ConnectionSadd((uint32)(self0), (*uint8)(key0), (uint32)(key1), (*string)(values0), (uint32)(values1), &result)
	return
}

// Set represents the imported method "set".
//
// Set key to value.
//
// If key already holds a value, it is overwritten.
//
//	set: func(key: string, value: payload) -> result<_, error>
//
//go:nosplit
func (self Connection) Set(key string, value Payload) (result cm.Result[Error, struct{}, Error]) {
	self0 := cm.Reinterpret[uint32](self)
	key0, key1 := cm.LowerString(key)
	value0, value1 := cm.LowerList(value)
	wasmimport_ConnectionSet((uint32)(self0), (*uint8)(key0), (uint32)(key1), (*uint8)(value0), (uint32)(value1), &result)
	return
}

// Smembers represents the imported method "smembers".
//
// Retrieve the contents of the set named `key`.
//
//	smembers: func(key: string) -> result<list<string>, error>
//
//go:nosplit
func (self Connection) Smembers(key string) (result cm.Result[ErrorShape, cm.List[string], Error]) {
	self0 := cm.Reinterpret[uint32](self)
	key0, key1 := cm.LowerString(key)
	wasmimport_ConnectionSmembers((uint32)(self0), (*uint8)(key0), (uint32)(key1), &result)
	return
}

// Srem represents the imported method "srem".
//
// Remove the specified `values` from the set named `key`, returning the number of
// newly-removed values.
//
//	srem: func(key: string, values: list<string>) -> result<u32, error>
//
//go:nosplit
func (self Connection) Srem(key string, values cm.List[string]) (result cm.Result[ErrorShape, uint32, Error]) {
	self0 := cm.Reinterpret[uint32](self)
	key0, key1 := cm.LowerString(key)
	values0, values1 := cm.LowerList(values)
	wasmimport_ConnectionSrem((uint32)(self0), (*uint8)(key0), (uint32)(key1), (*string)(values0), (uint32)(values1), &result)
	return
}

// Payload represents the list "fermyon:spin/redis@2.0.0#payload".
//
// The message payload.
//
//	type payload = list<u8>
type Payload cm.List[uint8]

// RedisParameter represents the variant "fermyon:spin/redis@2.0.0#redis-parameter".
//
// A parameter type for the general-purpose `execute` function.
//
//	variant redis-parameter {
//		int64(s64),
//		binary(payload),
//	}
type RedisParameter cm.Variant[uint8, Payload, int64]

// RedisParameterInt64 returns a [RedisParameter] of case "int64".
func RedisParameterInt64(data int64) RedisParameter {
	return cm.New[RedisParameter](0, data)
}

// Int64 returns a non-nil *[int64] if [RedisParameter] represents the variant case "int64".
func (self *RedisParameter) Int64() *int64 {
	return cm.Case[int64](self, 0)
}

// RedisParameterBinary returns a [RedisParameter] of case "binary".
func RedisParameterBinary(data Payload) RedisParameter {
	return cm.New[RedisParameter](1, data)
}

// Binary returns a non-nil *[Payload] if [RedisParameter] represents the variant case "binary".
func (self *RedisParameter) Binary() *Payload {
	return cm.Case[Payload](self, 1)
}

var stringsRedisParameter = [2]string{
	"int64",
	"binary",
}

// String implements [fmt.Stringer], returning the variant case name of v.
func (v RedisParameter) String() string {
	return stringsRedisParameter[v.Tag()]
}

// RedisResult represents the variant "fermyon:spin/redis@2.0.0#redis-result".
//
// A return type for the general-purpose `execute` function.
//
//	variant redis-result {
//		nil,
//		status(string),
//		int64(s64),
//		binary(payload),
//	}
type RedisResult cm.Variant[uint8, string, int64]

// RedisResultNil returns a [RedisResult] of case "nil".
func RedisResultNil() RedisResult {
	var data struct{}
	return cm.New[RedisResult](0, data)
}

// Nil returns true if [RedisResult] represents the variant case "nil".
func (self *RedisResult) Nil() bool {
	return self.Tag() == 0
}

// RedisResultStatus returns a [RedisResult] of case "status".
func RedisResultStatus(data string) RedisResult {
	return cm.New[RedisResult](1, data)
}

// Status returns a non-nil *[string] if [RedisResult] represents the variant case "status".
func (self *RedisResult) Status() *string {
	return cm.Case[string](self, 1)
}

// RedisResultInt64 returns a [RedisResult] of case "int64".
func RedisResultInt64(data int64) RedisResult {
	return cm.New[RedisResult](2, data)
}

// Int64 returns a non-nil *[int64] if [RedisResult] represents the variant case "int64".
func (self *RedisResult) Int64() *int64 {
	return cm.Case[int64](self, 2)
}

// RedisResultBinary returns a [RedisResult] of case "binary".
func RedisResultBinary(data Payload) RedisResult {
	return cm.New[RedisResult](3, data)
}

// Binary returns a non-nil *[Payload] if [RedisResult] represents the variant case "binary".
func (self *RedisResult) Binary() *Payload {
	return cm.Case[Payload](self, 3)
}

var stringsRedisResult = [4]string{
	"nil",
	"status",
	"int64",
	"binary",
}

// String implements [fmt.Stringer], returning the variant case name of v.
func (v RedisResult) String() string {
	return stringsRedisResult[v.Tag()]
}
