// Code generated by wit-bindgen-go. DO NOT EDIT.

package redis

import (
	"go.bytecodealliance.org/cm"
)

// This file contains wasmimport and wasmexport declarations for "fermyon:spin@2.0.0".

//go:wasmimport fermyon:spin/redis@2.0.0 [resource-drop]connection
//go:noescape
func wasmimport_ConnectionResourceDrop(self0 uint32)

//go:wasmimport fermyon:spin/redis@2.0.0 [static]connection.open
//go:noescape
func wasmimport_ConnectionOpen(address0 *uint8, address1 uint32, result *cm.Result[ErrorShape, Connection, Error])

//go:wasmimport fermyon:spin/redis@2.0.0 [method]connection.del
//go:noescape
func wasmimport_ConnectionDel(self0 uint32, keys0 *string, keys1 uint32, result *cm.Result[ErrorShape, uint32, Error])

//go:wasmimport fermyon:spin/redis@2.0.0 [method]connection.execute
//go:noescape
func wasmimport_ConnectionExecute(self0 uint32, command0 *uint8, command1 uint32, arguments0 *RedisParameter, arguments1 uint32, result *cm.Result[ErrorShape, cm.List[RedisResult], Error])

//go:wasmimport fermyon:spin/redis@2.0.0 [method]connection.get
//go:noescape
func wasmimport_ConnectionGet(self0 uint32, key0 *uint8, key1 uint32, result *cm.Result[OptionPayloadShape, cm.Option[Payload], Error])

//go:wasmimport fermyon:spin/redis@2.0.0 [method]connection.incr
//go:noescape
func wasmimport_ConnectionIncr(self0 uint32, key0 *uint8, key1 uint32, result *cm.Result[ErrorShape, int64, Error])

//go:wasmimport fermyon:spin/redis@2.0.0 [method]connection.publish
//go:noescape
func wasmimport_ConnectionPublish(self0 uint32, channel0 *uint8, channel1 uint32, payload0 *uint8, payload1 uint32, result *cm.Result[Error, struct{}, Error])

//go:wasmimport fermyon:spin/redis@2.0.0 [method]connection.sadd
//go:noescape
func wasmimport_ConnectionSadd(self0 uint32, key0 *uint8, key1 uint32, values0 *string, values1 uint32, result *cm.Result[ErrorShape, uint32, Error])

//go:wasmimport fermyon:spin/redis@2.0.0 [method]connection.set
//go:noescape
func wasmimport_ConnectionSet(self0 uint32, key0 *uint8, key1 uint32, value0 *uint8, value1 uint32, result *cm.Result[Error, struct{}, Error])

//go:wasmimport fermyon:spin/redis@2.0.0 [method]connection.smembers
//go:noescape
func wasmimport_ConnectionSmembers(self0 uint32, key0 *uint8, key1 uint32, result *cm.Result[ErrorShape, cm.List[string], Error])

//go:wasmimport fermyon:spin/redis@2.0.0 [method]connection.srem
//go:noescape
func wasmimport_ConnectionSrem(self0 uint32, key0 *uint8, key1 uint32, values0 *string, values1 uint32, result *cm.Result[ErrorShape, uint32, Error])
