spin_manifest_version = 2

[application]
authors = ["Patrick Jiang <patrickjiang0530@gmail.com>"]
description = ""
name = "pg-outbound-example"
version = "0.1.0"

[[trigger.http]]
route = "/..."
component = "pg-outbound"

[component.pg-outbound]
environment = { DB_URL = "host=localhost user=postgres dbname=spin_dev" }
source = "main.wasm"
allowed_outbound_hosts = ["postgres://localhost"]
[component.pg-outbound.build]
command = "tinygo build -target=wasip1 -gc=leaking -buildmode=c-shared -no-debug -o main.wasm ."
watch = ["**/*.go", "go.mod"]
