// Code generated by wit-bindgen-go. DO NOT EDIT.

// Package redis represents the imported interface "fermyon:spin/redis".
package redis

import (
	redistypes "github.com/fermyon/spin-go-sdk/v2/internal/fermyon/spin/redis-types"
	"go.bytecodealliance.org/cm"
)

// Payload represents the type alias "fermyon:spin/redis#payload".
//
// See [redistypes.Payload] for more information.
type Payload = redistypes.Payload

// RedisParameter represents the type alias "fermyon:spin/redis#redis-parameter".
//
// See [redistypes.RedisParameter] for more information.
type RedisParameter = redistypes.RedisParameter

// RedisResult represents the type alias "fermyon:spin/redis#redis-result".
//
// See [redistypes.RedisResult] for more information.
type RedisResult = redistypes.RedisResult

// Error represents the type alias "fermyon:spin/redis#error".
//
// See [redistypes.Error] for more information.
type Error = redistypes.Error

// Publish represents the imported function "publish".
//
// Publish a Redis message to the specificed channel and return an error, if any.
//
//	publish: func(address: string, channel: string, payload: payload) -> result<_,
//	error>
//
//go:nosplit
func Publish(address string, channel string, payload Payload) (result cm.Result[Error, struct{}, Error]) {
	address0, address1 := cm.LowerString(address)
	channel0, channel1 := cm.LowerString(channel)
	payload0, payload1 := cm.LowerList(payload)
	wasmimport_Publish((*uint8)(address0), (uint32)(address1), (*uint8)(channel0), (uint32)(channel1), (*uint8)(payload0), (uint32)(payload1), &result)
	return
}

// Get represents the imported function "get".
//
// Get the value of a key.
//
//	get: func(address: string, key: string) -> result<payload, error>
//
//go:nosplit
func Get(address string, key string) (result cm.Result[redistypes.Payload, Payload, Error]) {
	address0, address1 := cm.LowerString(address)
	key0, key1 := cm.LowerString(key)
	wasmimport_Get((*uint8)(address0), (uint32)(address1), (*uint8)(key0), (uint32)(key1), &result)
	return
}

// Set represents the imported function "set".
//
// Set key to value. If key alreads holds a value, it is overwritten.
//
//	set: func(address: string, key: string, value: payload) -> result<_, error>
//
//go:nosplit
func Set(address string, key string, value Payload) (result cm.Result[Error, struct{}, Error]) {
	address0, address1 := cm.LowerString(address)
	key0, key1 := cm.LowerString(key)
	value0, value1 := cm.LowerList(value)
	wasmimport_Set((*uint8)(address0), (uint32)(address1), (*uint8)(key0), (uint32)(key1), (*uint8)(value0), (uint32)(value1), &result)
	return
}

// Incr represents the imported function "incr".
//
// Increments the number stored at key by one. If the key does not exist, it is set
// to 0 before performing the operation.
// An error is returned if the key contains a value of the wrong type or contains
// a string that can not be represented as integer.
//
//	incr: func(address: string, key: string) -> result<s64, error>
//
//go:nosplit
func Incr(address string, key string) (result cm.Result[int64, int64, Error]) {
	address0, address1 := cm.LowerString(address)
	key0, key1 := cm.LowerString(key)
	wasmimport_Incr((*uint8)(address0), (uint32)(address1), (*uint8)(key0), (uint32)(key1), &result)
	return
}

// Del represents the imported function "del".
//
// Removes the specified keys. A key is ignored if it does not exist.
//
//	del: func(address: string, keys: list<string>) -> result<s64, error>
//
//go:nosplit
func Del(address string, keys cm.List[string]) (result cm.Result[int64, int64, Error]) {
	address0, address1 := cm.LowerString(address)
	keys0, keys1 := cm.LowerList(keys)
	wasmimport_Del((*uint8)(address0), (uint32)(address1), (*string)(keys0), (uint32)(keys1), &result)
	return
}

// Sadd represents the imported function "sadd".
//
// Add the specified `values` to the set named `key`, returning the number of newly-added
// values.
//
//	sadd: func(address: string, key: string, values: list<string>) -> result<s64, error>
//
//go:nosplit
func Sadd(address string, key string, values cm.List[string]) (result cm.Result[int64, int64, Error]) {
	address0, address1 := cm.LowerString(address)
	key0, key1 := cm.LowerString(key)
	values0, values1 := cm.LowerList(values)
	wasmimport_Sadd((*uint8)(address0), (uint32)(address1), (*uint8)(key0), (uint32)(key1), (*string)(values0), (uint32)(values1), &result)
	return
}

// Smembers represents the imported function "smembers".
//
// Retrieve the contents of the set named `key`.
//
//	smembers: func(address: string, key: string) -> result<list<string>, error>
//
//go:nosplit
func Smembers(address string, key string) (result cm.Result[cm.List[string], cm.List[string], Error]) {
	address0, address1 := cm.LowerString(address)
	key0, key1 := cm.LowerString(key)
	wasmimport_Smembers((*uint8)(address0), (uint32)(address1), (*uint8)(key0), (uint32)(key1), &result)
	return
}

// Srem represents the imported function "srem".
//
// Remove the specified `values` from the set named `key`, returning the number of
// newly-removed values.
//
//	srem: func(address: string, key: string, values: list<string>) -> result<s64, error>
//
//go:nosplit
func Srem(address string, key string, values cm.List[string]) (result cm.Result[int64, int64, Error]) {
	address0, address1 := cm.LowerString(address)
	key0, key1 := cm.LowerString(key)
	values0, values1 := cm.LowerList(values)
	wasmimport_Srem((*uint8)(address0), (uint32)(address1), (*uint8)(key0), (uint32)(key1), (*string)(values0), (uint32)(values1), &result)
	return
}

// Execute represents the imported function "execute".
//
// Execute an arbitrary Redis command and receive the result.
//
//	execute: func(address: string, command: string, arguments: list<redis-parameter>)
//	-> result<list<redis-result>, error>
//
//go:nosplit
func Execute(address string, command string, arguments cm.List[RedisParameter]) (result cm.Result[cm.List[RedisResult], cm.List[RedisResult], Error]) {
	address0, address1 := cm.LowerString(address)
	command0, command1 := cm.LowerString(command)
	arguments0, arguments1 := cm.LowerList(arguments)
	wasmimport_Execute((*uint8)(address0), (uint32)(address1), (*uint8)(command0), (uint32)(command1), (*RedisParameter)(arguments0), (uint32)(arguments1), &result)
	return
}
