// Code generated by wit-bindgen-go. DO NOT EDIT.

//go:build !wasip1

package keyvalue

import (
	"unsafe"
)

// ErrorShape is used for storage in variant or result types.
type ErrorShape struct {
	shape [unsafe.Sizeof(Error{})]byte
}
