// Code generated by wit-bindgen-go. DO NOT EDIT.

package mqtt

import (
	"go.bytecodealliance.org/cm"
)

// This file contains wasmimport and wasmexport declarations for "fermyon:spin@2.0.0".

//go:wasmimport fermyon:spin/mqtt@2.0.0 [resource-drop]connection
//go:noescape
func wasmimport_ConnectionResourceDrop(self0 uint32)

//go:wasmimport fermyon:spin/mqtt@2.0.0 [static]connection.open
//go:noescape
func wasmimport_ConnectionOpen(address0 *uint8, address1 uint32, username0 *uint8, username1 uint32, password0 *uint8, password1 uint32, keepAliveIntervalInSecs0 uint64, result *cm.Result[ErrorShape, Connection, Error])

//go:wasmimport fermyon:spin/mqtt@2.0.0 [method]connection.publish
//go:noescape
func wasmimport_ConnectionPublish(self0 uint32, topic0 *uint8, topic1 uint32, payload0 *uint8, payload1 uint32, qos0 uint32, result *cm.Result[Error, struct{}, Error])
