spin_manifest_version = 2

[application]
authors = ["Patrick Jiang <patrickjiang0530@gmail.com>"]
description = ""
name = "mysql-outbound-example"
version = "0.1.0"

[[trigger.http]]
route = "/..."
component = "mysql"

[component.mysql]
environment = { DB_URL = "mysql://spin:spin@127.0.0.1/spin_dev" }
source = "main.wasm"
allowed_outbound_hosts = ["mysql://127.0.0.1"]
[component.mysql.build]
command = "tinygo build -target=wasi -gc=leaking -o main.wasm main.go"
watch = ["**/*.go", "go.mod"]
