// Code generated by wit-bindgen-go. DO NOT EDIT.

package keyvalue

import (
	"go.bytecodealliance.org/cm"
)

// This file contains wasmimport and wasmexport declarations for "fermyon:spin".

//go:wasmimport fermyon:spin/key-value open
//go:noescape
func wasmimport_Open(name0 *uint8, name1 uint32, result *cm.Result[ErrorShape, Store, Error])

//go:wasmimport fermyon:spin/key-value get
//go:noescape
func wasmimport_Get(store0 uint32, key0 *uint8, key1 uint32, result *cm.Result[ErrorShape, cm.List[uint8], Error])

//go:wasmimport fermyon:spin/key-value set
//go:noescape
func wasmimport_Set(store0 uint32, key0 *uint8, key1 uint32, value0 *uint8, value1 uint32, result *cm.Result[Error, struct{}, Error])

//go:wasmimport fermyon:spin/key-value delete
//go:noescape
func wasmimport_Delete(store0 uint32, key0 *uint8, key1 uint32, result *cm.Result[Error, struct{}, Error])

//go:wasmimport fermyon:spin/key-value exists
//go:noescape
func wasmimport_Exists(store0 uint32, key0 *uint8, key1 uint32, result *cm.Result[ErrorShape, bool, Error])

//go:wasmimport fermyon:spin/key-value get-keys
//go:noescape
func wasmimport_GetKeys(store0 uint32, result *cm.Result[ErrorShape, cm.List[string], Error])

//go:wasmimport fermyon:spin/key-value close
//go:noescape
func wasmimport_Close(store0 uint32)
