// Code generated by wit-bindgen-go. DO NOT EDIT.

package mysql

import (
	rdbmstypes "github.com/fermyon/spin-go-sdk/v2/internal/fermyon/spin/v2.0.0/rdbms-types"
	"go.bytecodealliance.org/cm"
	"unsafe"
)

// ErrorShape is used for storage in variant or result types.
type ErrorShape struct {
	_     cm.HostLayout
	shape [unsafe.Sizeof(rdbmstypes.Error{})]byte
}

// RowSetShape is used for storage in variant or result types.
type RowSetShape struct {
	_     cm.HostLayout
	shape [unsafe.Sizeof(rdbmstypes.RowSet{})]byte
}
