// Code generated by wit-bindgen-go. DO NOT EDIT.

package mysql

import (
	"go.bytecodealliance.org/cm"
)

// This file contains wasmimport and wasmexport declarations for "fermyon:spin@2.0.0".

//go:wasmimport fermyon:spin/mysql@2.0.0 [resource-drop]connection
//go:noescape
func wasmimport_ConnectionResourceDrop(self0 uint32)

//go:wasmimport fermyon:spin/mysql@2.0.0 [static]connection.open
//go:noescape
func wasmimport_ConnectionOpen(address0 *uint8, address1 uint32, result *cm.Result[ErrorShape, Connection, Error])

//go:wasmimport fermyon:spin/mysql@2.0.0 [method]connection.execute
//go:noescape
func wasmimport_ConnectionExecute(self0 uint32, statement0 *uint8, statement1 uint32, params0 *ParameterValue, params1 uint32, result *cm.Result[Error, struct{}, Error])

//go:wasmimport fermyon:spin/mysql@2.0.0 [method]connection.query
//go:noescape
func wasmimport_ConnectionQuery(self0 uint32, statement0 *uint8, statement1 uint32, params0 *ParameterValue, params1 uint32, result *cm.Result[RowSetShape, RowSet, Error])
