name: Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23'

      - name: Setup TinyGo
        uses: acifani/setup-tinygo@v2
        with:
          tinygo-version: '0.35.0'

      - name: Setup Spin
        uses: fermyon/actions/spin/setup@v1
        with:
          version: "v3.1.2"

      - name: Setup Wasmtime
        uses: bytecodealliance/actions/wasmtime/setup@v1
        with:
          version: "28.0.0"

      - name: Run unit tests
        run: make test

      - name: Run integration tests
        run: make test-integration
