// Code generated by wit-bindgen-go. DO NOT EDIT.

//go:build !wasip1

package inboundhttp

import (
	httptypes "github.com/fermyon/spin-go-sdk/internal/fermyon/spin/http-types"
	"github.com/ydnar/wasm-tools-go/cm"
)

func lift_OptionBody(f0 uint32, f1 *uint8, f2 uint32) (v cm.Option[httptypes.Body]) {
	if f0 == 0 {
		return
	}
	return cm.Some[cm.Option[httptypes.Body]](cm.LiftList[httptypes.Body]((*uint8)(f1), (uint32)(f2)))
}

func lift_Request(f0 uint32, f1 *uint8, f2 uint32, f3 *[2]string, f4 uint32, f5 *[2]string, f6 uint32, f7 uint32, f8 *uint8, f9 uint32) (v httptypes.Request) {
	v.Method = (httptypes.Method)(f0)
	v.URI = cm.LiftString[httptypes.URI](f1, f2)
	v.Headers = cm.LiftList[httptypes.Headers](f3, f4)
	v.Params = cm.LiftList[httptypes.Params](f5, f6)
	v.Body = lift_OptionBody(f7, f8, f9)
	return
}
